name: Pull Spotify Playlist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spotipy

      - name: Pull playlist data
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          python code_folder/__init__.py
      
      - name: Upload playlist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: data_folder
